version: '3'
services:
  redis:
    image: redis:alpine
    container_name: dev-redis
    restart: always
    ports:
      - 6379:6379
    networks: 
      - devnet
      
  rabbit-mq:
    image: rabbitmq:management-alpine
    container_name: dev-rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - devnet

  couch-db:
    container_name: dev-couchdb
    image: klaemo/couchdb:latest
    restart: always
    volumes:
      - ./couchdb/local:/opt/couchdb/etc/local.d
      - ./couchdb/data:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      - devnet

networks:
  devnet:
